package dbschema

import (
	"strings"
	"testing"
)

func TestGenerateTableDDL(t *testing.T) {
	table := TableDef{
		DatabaseName: "db_test",
		TableName:    "pengguna",
		Engine:       EngineMySQL,
		IncludeDrop:  true,
		Columns: []ColumnDef{
			{Name: "id", Type: TypeAutoID, IsPrimaryKey: true, IsNotNull: true},
			{Name: "email", Type: TypeVarchar, Length: "100", IsNotNull: true, IsUnique: true},
			{Name: "saldo", Type: TypeDecimal, Length: "12,2", IsNotNull: true, DefaultValue: "0.00"},
			{Name: "is_active", Type: TypeBoolean, IsNotNull: true, DefaultValue: "1"},
			{Name: "created_at", Type: TypeDateTime, IsNotNull: true, DefaultValue: "CURRENT_TIMESTAMP"},
		},
	}

	// 1. Test MySQL
	sqlMySQL := GenerateTableDDL(table)
	if !strings.Contains(sqlMySQL, "CREATE TABLE `pengguna`") {
		t.Errorf("Expected MySQL CREATE TABLE syntax, got:\n%s", sqlMySQL)
	}
	if !strings.Contains(sqlMySQL, "BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY") {
		t.Errorf("Expected MySQL auto_increment PK, got:\n%s", sqlMySQL)
	}
	if !strings.Contains(sqlMySQL, "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4") {
		t.Errorf("Expected InnoDB suffix, got:\n%s", sqlMySQL)
	}

	// 2. Test PostgreSQL
	table.Engine = EnginePostgres
	sqlPG := GenerateTableDDL(table)
	if !strings.Contains(sqlPG, "CREATE TABLE \"pengguna\"") {
		t.Errorf("Expected Postgres CREATE TABLE syntax, got:\n%s", sqlPG)
	}
	if !strings.Contains(sqlPG, "BIGSERIAL PRIMARY KEY") {
		t.Errorf("Expected Postgres BIGSERIAL, got:\n%s", sqlPG)
	}
	if !strings.Contains(sqlPG, "NUMERIC(12,2)") {
		t.Errorf("Expected Postgres NUMERIC, got:\n%s", sqlPG)
	}

	// 3. Test SQLite
	table.Engine = EngineSQLite
	sqlSQLite := GenerateTableDDL(table)
	if !strings.Contains(sqlSQLite, "INTEGER PRIMARY KEY AUTOINCREMENT") {
		t.Errorf("Expected SQLite AUTOINCREMENT, got:\n%s", sqlSQLite)
	}

	// 4. Test SQL Server
	table.Engine = EngineSQLServer
	sqlMSSQL := GenerateTableDDL(table)
	if !strings.Contains(sqlMSSQL, "[pengguna]") {
		t.Errorf("Expected SQL Server bracket quotes, got:\n%s", sqlMSSQL)
	}
	if !strings.Contains(sqlMSSQL, "BIGINT IDENTITY(1,1) PRIMARY KEY") {
		t.Errorf("Expected SQL Server IDENTITY, got:\n%s", sqlMSSQL)
	}

	// 5. Test Oracle
	table.Engine = EngineOracle
	sqlOracle := GenerateTableDDL(table)
	if !strings.Contains(sqlOracle, "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY") {
		t.Errorf("Expected Oracle IDENTITY syntax, got:\n%s", sqlOracle)
	}
}

func TestSearchCommands(t *testing.T) {
	// Search by keyword
	res := SearchCommands(EngineAll, CatAll, "utf8mb4")
	if len(res) == 0 {
		t.Errorf("Expected at least 1 result for utf8mb4 query")
	}

	// Search by category
	resCat := SearchCommands(EngineMySQL, CatUserPrivileges, "")
	if len(resCat) == 0 {
		t.Errorf("Expected user privileges commands for MySQL")
	}

	// Search non-existent
	resNone := SearchCommands(EngineAll, CatAll, "xyz123_non_existent")
	if len(resNone) != 0 {
		t.Errorf("Expected 0 results for non-existent keyword, got %d", len(resNone))
	}
}

func TestSearchDataTypes(t *testing.T) {
	res := SearchDataTypes("UUID")
	if len(res) == 0 {
		t.Errorf("Expected to find UUID data type mapping")
	}
	found := false
	for _, r := range res {
		if strings.Contains(r.LogicalType, "UUID") {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("UUID not found in search results")
	}
}

func TestSchemaTemplates(t *testing.T) {
	templates := GetSchemaTemplates()
	if len(templates) < 4 {
		t.Errorf("Expected at least 4 schema templates, got %d", len(templates))
	}

	tmpl := templates[0]
	rendered := tmpl.RenderScript(EngineMySQL, "db_custom", "tbl_")
	if !strings.Contains(rendered, "db_custom") {
		t.Errorf("Expected custom DB name in rendered script")
	}
	if !strings.Contains(rendered, "tbl_") {
		t.Errorf("Expected custom table prefix in rendered script")
	}
}

func TestCommandParameterRendering(t *testing.T) {
	cmds := GetCommandCatalog()
	if len(cmds) == 0 {
		t.Fatalf("Expected non-empty command catalog")
	}

	cmd := cmds[0]
	custom := cmd.RenderCommand(map[string]string{
		"DB_NAME": "db_my_school",
	})
	if !strings.Contains(custom, "db_my_school") {
		t.Errorf("Expected placeholder substitution with db_my_school, got:\n%s", custom)
	}
}
